<?php
/**
 * CustomerApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Bamba
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bamba API
 *
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.2.9
 * Contact: desarrollo@vivebamba.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Bamba\Test\Api;

use \Bamba\Configuration;
use \Bamba\ApiException;
use \Bamba\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Bamba
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1CustomerCustomerIdServicesGet
     *
     * Get customer services.
     *
     */
    public function testV1CustomerCustomerIdServicesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1CustomerCustomerIdServicesSkuCancelPut
     *
     * Cancel customer services.
     *
     */
    public function testV1CustomerCustomerIdServicesSkuCancelPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
